# Generated by Django 5.2.9 on 2025-12-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barconfig',
            name='max_workers_per_hour',
            field=models.IntegerField(default=4),
        ),
    ]
