# Generated by Django 5.2.9 on 2025-12-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_barconfig_max_workers_per_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barconfig',
            name='closing_hour',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='barconfig',
            name='opening_hour',
            field=models.IntegerField(default=4),
        ),
    ]
