# Generated by Django 5.2.9 on 2025-12-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_barconfig_closing_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barconfig',
            name='closed_days',
            field=models.JSONField(default=list),
        ),
    ]
