# Generated by Django 5.2.9 on 2025-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_barconfig_closed_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='max_hours_per_week',
        ),
        migrations.AddField(
            model_name='worker',
            name='min_hours_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
